#!/bin/bash

set -e

BALANCE_PATH="$(dirname $0)/balance"

if [ -z $BALANCE_WATCH_INTERVAL ]; then
  BALANCE_WATCH_INTERVAL=1
fi

watch -n $BALANCE_WATCH_INTERVAL --color "$BALANCE_PATH \^Assets Credit"
