#!/bin/bash

set -e

REGISTER_PATH="$(dirname $0)/register"

if [ -z $BUDGET_FILE ]; then
  echo '$BUDGET_FILE not properly set. Please check your environment.'
  exit 99
fi

THIRTY_DAYS_AGO=$( date -v -30d "+%Y/%m/%d" )

$REGISTER_PATH --begin "$THIRTY_DAYS_AGO" "$@"
